=== timmcginley/V3/data/bimSubCases_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "array",
    "title": "The Root Schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": [],
    "additionalItems": true,
    "items": {
        "$id": "#/items",
        "type": "object",
        "title": "The Items Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": {},
        "examples": [
            {
                "aim": "to represent or preserve the current status of the facility and facility elements.",
                "desc": "BIM is often used to capture geometric and attribute data about a facility. This can be done using a number of methods and at a number of points during the life of a facility: the elements of the site prior to the development of a new facility or the conditions of an existing facility prior to renovation. Data could be captured using a laser scanner or recorded manually by inputting model and serial numbers into a spreadsheet. The common factor within this purposes of BIM Uses is that data is captured where no data existed prior. However, it is not newly generated information, rather creating a record of the facility elements that exists.",
                "name": "Capture",
                "synonyms": [
                    "collect"
                ],
                "major": "Gather"
            },
            {
                "aim": "to express or measure the amount of a facility element.",
                "desc": "In this purpose of BIM Uses, BIM is used for counting or collecting the amount of specific facility elements. This purpose is often used as part of the estimating and cost forecasting process. During the design phase of a facility, quantities maybe be defined broadly, represented by a range and subject to change. In the construction phase, quantities become more certain and in the operations phase, quantities of elements can be readily calculated, say for instance. For example, the area of carpet to be replaced or the vacant space which is available and rentable, the exact area and dimensions should be known.",
                "name": "Quantify",
                "synonyms": [
                    "quantity takeoff"
                ],
                "major": "Gather"
            },
            {
                "name": "Monitor",
                "synonyms": [
                    "observe",
                    "measure"
                ],
                "major": "Gather",
                "aim": "to collect information regarding the performance of facility elements and systems.",
                "desc": "BIM can be used to monitor real-time performance data of facility elements and facility activities. This purpose of BIM Uses includes those domain uses in which BIM is implemented to understand the performance of particular facility elements or processes. For example, during the operations phase of a facility, BIM can be used to monitor the temperature of a space. It is in this purpose of BIM Uses where Building Automation System data is integrated with the BIM data. Or in construction, BIM could be used to monitor the productivity of a construction process. It is in this purpose of BIM Uses that dynamic real-time data is collected to support decision making."
            }
        ],
        "additionalProperties": true,
        "required": [
            "name",
            "major",
            "aim",
            "desc",
            "synonyms"
        ],
        "properties": {
            "name": {
                "$id": "#/items/properties/name",
                "type": "string",
                "title": "The Name Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "Capture"
                ]
            },
            "major": {
                "$id": "#/items/properties/major",
                "type": "string",
                "title": "The Major Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "Gather"
                ]
            },
            "aim": {
                "$id": "#/items/properties/aim",
                "type": "string",
                "title": "The Aim Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "to represent or preserve the current status of the facility and facility elements."
                ]
            },
            "desc": {
                "$id": "#/items/properties/desc",
                "type": "string",
                "title": "The Desc Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "BIM is often used to capture geometric and attribute data about a facility. This can be done using a number of methods and at a number of points during the life of a facility: the elements of the site prior to the development of a new facility or the conditions of an existing facility prior to renovation. Data could be captured using a laser scanner or recorded manually by inputting model and serial numbers into a spreadsheet. The common factor within this purposes of BIM Uses is that data is captured where no data existed prior. However, it is not newly generated information, rather creating a record of the facility elements that exists."
                ]
            },
            "synonyms": {
                "$id": "#/items/properties/synonyms",
                "type": "array",
                "title": "The Synonyms Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": [],
                "examples": [
                    [
                        "collect"
                    ]
                ],
                "additionalItems": true,
                "items": {
                    "$id": "#/items/properties/synonyms/items",
                    "type": "string",
                    "title": "The Items Schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "collect"
                    ]
                }
            }
        }
    }
}

=== timmcginley/V3/data/bimSubCases.json
[{
		"name": "Capture",
		"major": "Gather",
		"aim": "to represent or preserve the current status of the facility and facility elements.",
		"desc": "BIM is often used to capture geometric and attribute data about a facility. This can be done using a number of methods and at a number of points during the life of a facility: the elements of the site prior to the development of a new facility or the conditions of an existing facility prior to renovation. Data could be captured using a laser scanner or recorded manually by inputting model and serial numbers into a spreadsheet. The common factor within this purposes of BIM Uses is that data is captured where no data existed prior. However, it is not newly generated information, rather creating a record of the facility elements that exists.",
		"synonyms": ["collect"]
	},
	{
		"name": "Quantify",
		"major": "Gather",
		"aim": "to express or measure the amount of a facility element.",
		"desc": "In this purpose of BIM Uses, BIM is used for counting or collecting the amount of specific facility elements. This purpose is often used as part of the estimating and cost forecasting process. During the design phase of a facility, quantities maybe be defined broadly, represented by a range and subject to change. In the construction phase, quantities become more certain and in the operations phase, quantities of elements can be readily calculated, say for instance. For example, the area of carpet to be replaced or the vacant space which is available and rentable, the exact area and dimensions should be known.",
		"synonyms": ["quantity takeoff"]
	},
	{
		"name": "Monitor",
		"major": "Gather",
		"aim": "to collect information regarding the performance of facility elements and systems.",
		"desc": "BIM can be used to monitor real-time performance data of facility elements and facility activities. This purpose of BIM Uses includes those domain uses in which BIM is implemented to understand the performance of particular facility elements or processes. For example, during the operations phase of a facility, BIM can be used to monitor the temperature of a space. It is in this purpose of BIM Uses where Building Automation System data is integrated with the BIM data. Or in construction, BIM could be used to monitor the productivity of a construction process. It is in this purpose of BIM Uses that dynamic real-time data is collected to support decision making.",
		"synonyms": ["observe", "measure"]
	},
	{
		"name": "Qualify",
		"major": "Gather",
		"aim": "to characterize or identify facility elements’ status.",
		"desc": "For this BIM Use Purpose, the status of a facility element is tracked. This includes information such as: does this element exist within the facility? How is it working? This BIM Use Purpose tracks facility elements over time. For example, in design, what is the element’s level of development? In construction, has the element been fabricated? Is it installed? Is it damaged? During operations, this BIM Use Purpose can collect warranty information on the element and whether or not the element is reaching the end of its useful life.",
		"synonyms": ["follow", "track", "identify"]
	},
	{
		"name": "Prescribe",
		"major": "Generate",
		"aim": "to determine the need for and select specific facility elements.",
		"desc": "The prescribing purpose of BIM Uses is used when a generator determines there is a need for a specific facility element. The programmer or architect of the facility may prescribe the need for certain rooms or spaces in the facility. While the mechanical engineer may prescribe the need for a specific HVAC system. The contractor could determine the need for a temporary construction element such as a tower crane, and the operator of the facility may prescribe a specific replacement part for the facility. The element prescribed depends on a number of factors such as phase, discipline, and level of development.",
		"synonyms": ["program", "specify"]
	},
	{
		"name": "Arrange",
		"major": "Generate",
		"aim": "to determine location and placement of facility elements.",
		"desc": "The arranging purpose of BIM Uses includes those Uses in which a location or configuration of a facility element is determined. During the planning phase of a facility's life, this could be the arrangement or adjacency of specific spaces within a proposed facility. During the design phase, it could be the general location of fire protection piping. While in the construction phase, it could include the placement of the hangers that support that piping. This could also be used during the operations phase to determine the placement of furniture systems. In general terms, any time a geometric location of element is determine, it is being arranged.",
		"synonyms": ["configure", "lay out", "locate", "place"]
	},
	{
		"name": "Size",
		"major": "Generate",
		"aim": "to determine the magnitude and scale of facility elements.",
		"desc": "The sizing purpose of BIM Uses is in use when the magnitude of a facility element is determined. Some of those elements during design could include the dimensions of spaces, the shape of a steel beam, or the size of ductwork. During construction, it could include the size of a crane or the thickness of duct insulation. Additionally, during operations, facility managers record the size of replacement parts or modifications to the facility.",
		"synonyms": ["scale", "engineer"]
	},
	{
		"name": "Coordinate",
		"major": "Analyse",
		"aim": "to ensure the efficiency and harmony of the relationship of facility elements.",
		"desc": "The coordinating purpose of BIM Uses include those uses where facility elements are analyzed to ensure their relationship to other elements is effective and in harmony. This purpose of BIM Uses is often called clash detection, collision avoidance, design coordination, and interference management, among others. Ultimately, all of the facility elements should work in conjunction with one another. This can include coordinating design intent of various systems during design, coordinating fabrication and installation during construction or coordinating existing operations while renovations are underway. Overall this purpose of BIM uses ensures that the facility will fit together as it is planned and that all the various systems have been considered.",
		"synonyms": ["detect", "avoid"]
	},
	{
		"name": "Forecast",
		"major": "Analyse",
		"aim": "to predict the future performance of the facility and facility elements.",
		"desc": "This purpose of BIM Uses is one of the largest and has the most variance in its application from element to element. Within this purpose of BIM Uses, detail analysis is conducted to predict future performance of the facility and facility elements. Some of the primary performance factors that should be considered include financial, energy, flow, scenario, and temporal. Financial forecasting includes cost estimation of first cost of construction as well as the life cycle cost of a facility. Energy forecasting predicts how future energy consumption and flow forecasting predicts performance such as air flow or occupant/crowd circulation. Scenario forecasting predicts performance of the facility during emergencies, such as fire, flood, evacuation, and others. Temporal forecasting predicts the performance of the facility over time to include building degradation and the timing for element replacement. Together this purpose of BIM Uses examines multiple facility variables predicts facility performance.",
		"synonyms": ["simulate", "predict"]
	},
	{
		"name": "Validate",
		"major": "Analyse",
		"aim": "to check or prove accuracy of facility information and that is logical and reasonable.",
		"desc": "This purpose of BIM Uses is implemented to validate facility information. This includes purpose checking facility information for accuracy to ensure that it is logical and reasonable. The validating BIM Uses fall into three primary areas: prescription, functionality, and compliance validation. Prescription validation ensures that facility has the elements that were specified and programmed within the facility including the primary element of facility spaces or rooms. The purpose of functionality validation is to ensure that the facility is constructible, maintainable, and usable. Will the facility perform the purpose for which it has been designed? Compliance validation confirms a facility's compliance with codes and standards to include building codes, ADA standards, sustainability standards and others. Anytime facility information that was developed in another process is checked for accuracy, it falls into the category of validating.",
		"synonyms": ["check", "confirm"]
	},
	{
		"name": "Visualize",
		"major": "Communicate",
		"aim": "to form a realistic representation of a facility or facility elements.",
		"desc": "As part of the communication purpose of BIM Uses, using BIM to better visualize a facility is very powerful. It is especially powerful for those who have not been trained within the design and construction industry but are critical stakeholders and decision makers. The visualization purpose of BIM Uses include those BIM Uses which are implemented to form a representation of the facility or facility elements. Often this visualization can be very realistic and detailed in nature. Visualization is often used to support decision making about the facility's design or construction as well as support marketing efforts. It can include walkthroughs, renderings, and schedule visualizations. The fact that the visualization is a byproduct of other BIM processes improves the ability of individuals to share facility information in a more effective manner with much additional effort. ",
		"synonyms": ["review"]
	},
	{
		"name": "Transform",
		"major": "Communicate",
		"aim": "to modify information and translate it to be received by another process ",
