=== timmcginley/V3/data/bimusecase_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "array",
    "title": "The Root Schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": [],
    "additionalItems": true,
    "items": {
        "$id": "#/items",
        "type": "object",
        "title": "The Items Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": {},
        "examples": [
            {
                "aim": "to collect or organize facility information",
                "desc": "BIM is often used to gather information about a facility at various phases during a facility’s life. Whether that is to count the specific amount of an element or determine the current status of a facility element in order to properly manage that asset, the use of BIM can greatly assist in this effort. This sub-purposes of BIM Uses include: Qualifying, Monitoring, Capturing, and Quantify. In this primary purpose of BIM Uses, the author is collecting, gathering and organizing information about the facility. This purpose of BIM Uses does not determine the meaning or make inferences about the meaning of the information gathered, rather it is solely focused on the collection and organization of the information. This is often the first step of a comprehensive series of BIM processes.",
                "name": "Gather",
                "synonyms": [
                    "administer",
                    "collect",
                    "manage",
                    "acquire"
                ]
            },
            {
                "aim": "to create or author information about the facility",
                "desc": "Within the lifecycle of a facility almost every discipline that interacts with the facility will generate information about the facility. This purpose of BIM Uses includes those where BIM is used to create or author information about the facility. It includes prescribing, arranging, and sizing facility elements to various levels of development. Within the design phase, the design team will be the primary generators of information, while in the construction phase, the subcontractors will generate most of the information. Additionally, in the operations phase, that information could be generated by those maintaining the facility when they update or change that facility. Anytime new information is authored, modeled, or created, it is generated.",
                "name": "Generate",
                "synonyms": [
                    "create",
                    "author",
                    "model"
                ]
            },
            {
                "name": "Analyse",
                "synonyms": [
                    "examine",
                    "evaluate"
                ],
                "aim": "to examine elements of the facility to gain a better understanding of it",
                "desc": "Elements of the facility often require further analysis to determine their viability for the facility. The analyzing purpose of BIM Uses includes those uses in which a methodical examination of the facility elements is needed. The Uses of this purpose include coordinating, forecasting, and validating. It is in these BIM Uses data is often taken from what was gathered or generated and put into the format into which it can be used for decision making."
            }
        ],
        "additionalProperties": true,
        "required": [
            "name",
            "aim",
            "desc",
            "synonyms"
        ],
        "properties": {
            "name": {
                "$id": "#/items/properties/name",
                "type": "string",
                "title": "The Name Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "Gather"
                ]
            },
            "aim": {
                "$id": "#/items/properties/aim",
                "type": "string",
                "title": "The Aim Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "to collect or organize facility information"
                ]
            },
            "desc": {
                "$id": "#/items/properties/desc",
                "type": "string",
                "title": "The Desc Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "BIM is often used to gather information about a facility at various phases during a facility’s life. Whether that is to count the specific amount of an element or determine the current status of a facility element in order to properly manage that asset, the use of BIM can greatly assist in this effort. This sub-purposes of BIM Uses include: Qualifying, Monitoring, Capturing, and Quantify. In this primary purpose of BIM Uses, the author is collecting, gathering and organizing information about the facility. This purpose of BIM Uses does not determine the meaning or make inferences about the meaning of the information gathered, rather it is solely focused on the collection and organization of the information. This is often the first step of a comprehensive series of BIM processes."
                ]
            },
            "synonyms": {
                "$id": "#/items/properties/synonyms",
                "type": "array",
                "title": "The Synonyms Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": [],
                "examples": [
                    [
                        "administer",
                        "collect",
                        "manage"
                    ]
                ],
                "additionalItems": true,
                "items": {
                    "$id": "#/items/properties/synonyms/items",
                    "type": "string",
                    "title": "The Items Schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "administer",
                        "collect",
                        "manage"
                    ]
                }
            }
        }
    }
}

=== timmcginley/V3/data/bimusecase.json
[{
		"name": "Gather",
		"aim": "to collect or organize facility information",
		"desc":"BIM is often used to gather information about a facility at various phases during a facilityâ€™s life. Whether that is to count the specific amount of an element or determine the current status of a facility element in order to properly manage that asset, the use of BIM can greatly assist in this effort. This sub-purposes of BIM Uses include: Qualifying, Monitoring, Capturing, and Quantify. In this primary purpose of BIM Uses, the author is collecting, gathering and organizing information about the facility. This purpose of BIM Uses does not determine the meaning or make inferences about the meaning of the information gathered, rather it is solely focused on the collection and organization of the information. This is often the first step of a comprehensive series of BIM processes.",
		"synonyms": ["administer", "collect", "manage", "acquire"]
	}, 
	{
		"name": "Generate",
		"aim": "to create or author information about the facility",
		"desc":"Within the lifecycle of a facility almost every discipline that interacts with the facility will generate information about the facility. This purpose of BIM Uses includes those where BIM is used to create or author information about the facility. It includes prescribing, arranging, and sizing facility elements to various levels of development. Within the design phase, the design team will be the primary generators of information, while in the construction phase, the subcontractors will generate most of the information. Additionally, in the operations phase, that information could be generated by those maintaining the facility when they update or change that facility. Anytime new information is authored, modeled, or created, it is generated.",
		"synonyms": ["create", "author", "model"]
	},
	{
		"name": "Analyse",
		"aim": "to examine elements of the facility to gain a better understanding of it",
		"desc":"Elements of the facility often require further analysis to determine their viability for the facility. The analyzing purpose of BIM Uses includes those uses in which a methodical examination of the facility elements is needed. The Uses of this purpose include coordinating, forecasting, and validating. It is in these BIM Uses data is often taken from what was gathered or generated and put into the format into which it can be used for decision making.",
		"synonyms": ["examine", "evaluate"]

	},
	{
		"name": "Communicate",
		"aim": "to present information about a facility in a method in which it can be shared or exchanged.",
		"desc":"One of the primary Uses of BIM is to communicate facility information. The communication purpose of BIM is intended to present information about a facility in a method which can be shared or exchanged. This is often the last step of many other processes when a visualization, transformation, drawing, or document is developed to communicate information from that process to the next user of that information. This is one of the most valuable uses of BIM. It promotes and enhances communication and often reduces the time it takes to communicate. Additionally, communication of the data is often a byproduct of the processes to accomplish other BIM Uses",
		"synonyms": ["exchange"]
	},
	{
		"name": "Realize",
		"aim": "to make or control a physical element using facility information",
		"desc":"BIM is beginning to allow the industry to remove the direct input of human interaction to develop specific elements of the facility. The realize purpose of BIM Uses includes those Use in which facility data (BIM data) is used to make or control a physical element of the facility. This BIM Use purpose gives the industry the ability to fabricate, assemble, control, and regulate elements of the facility. It is this ability that could eventually lead to the improved productivity of both construction and operations of facilities",
		"synonyms": ["implement", "perform", "execute"]
	}

]
