=== timmcginley/V3/data/courses_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "array",
    "title": "The Root Schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": [],
    "additionalItems": true,
    "items": {
        "type": "object",
        "title": "The Items Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": {},
        "examples": [
            {
                "course_code": "11000",
                "schedule": "E3B",
                "ECTS": "10",
                "name": "Engineering Work",
                "schedule2": "E5",
                "level": "BSc"
            },
            {
                "name": "Building Information Modeling (BIM)",
                "course_code": "11031",
                "level": "BSc",
                "schedule": "F3A",
                "ECTS": "5"
            },
            {
                "course_code": "1337",
                "level": "MSc",
                "schedule": "F3B",
                "ECTS": "5",
                "name": "Agile Building Design"
            }
        ],
        "additionalProperties": true,
        "required": [
            "name",
            "course_code",
            "level",
            "ECTS",
            "schedule"
        ],
        "properties": {
            "name": {
                "type": "string",
                "title": "The Name Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "Engineering Work"
                ]
            },
            "course_code": {
                "type": "string",
                "title": "The Course_code Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "11000"
                ]
            },
            "level": {
                "type": "string",
                "title": "The Level Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "BSc"
                ]
            },
            "ECTS": {
                "type": "string",
                "title": "The Ects Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "10"
                ]
            },
            "schedule": {
                "type": "string",
                "title": "The Schedule Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "E3B"
                ]
            },
            "schedule2": {
                "type": "string",
                "title": "The Schedule2 Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "E5"
                ]
            }
        }
    }
}

=== timmcginley/V3/data/courses.json
[

	{
		"name": "Engineering Work",
		"course_code": "11000",
		"level": "BSc",
		"ECTS": "10",
		"schedule": "E3B",
		"schedule2": "E5"
	},
	{
		"name": "Building Information Modeling (BIM)",
		"course_code": "11031",
		"level": "BSc",
		"ECTS": "5",
		"schedule": "F3A"
	},
	{
		"name": "Agile Building Design",
		"course_code": "1337",
		"level": "MSc",
		"ECTS": "5",
		"schedule": "F3B"
	},
	{
		"name": "Advanced Building Information Modeling (BIM)",
		"course_code": "11034",
		"level": "MSc",
		"ECTS": "5",
		"schedule": "E2A"
	},
	{
		"name": "Advanced BIM for Architectural Engineering",
		"course_code": "11035",
		"level": "BEng",
		"ECTS": "5",
		"schedule": "E5B"
	},
	{
		"name": "Advanced Building Design",
		"course_code": "11080",
		"level": "MSc",
		"ECTS": "10",
		"schedule": "F2A",
		"schedule2": "Jan"
	},
	{
		"name": "Master's Thesis",
		"course_code": "thesis",
		"level": "MSc",
		"ECTS": "30/35",
		"schedule": "F/E"
	},
	{
		"name": "BIM and visual communication",
		"course_code": "11951",
		"level": "BEng",
		"ECTS": "5",
		"schedule": "E5A"
	},
	{
		"name": "Building Information Modeling (BIM)",
		"course_code": "11952",
		"level": "BEng",
		"ECTS": "5",
		"schedule": "F3A"
	},
	{
		"name": "Ingeneering work",
		"course_code": "11990",
		"level": "BEng",
		"ECTS": "10",
		"schedule": "E5",
		"schedule2": "Jan"
	}

]
