=== timmcginley/V3/data/target_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "array",
    "title": "The Root Schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": [],
    "additionalItems": true,
    "items": {
        "$id": "#/items",
        "type": "object",
        "title": "The Items Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": {},
        "examples": [
            {
                "name": "Solar Decathalon",
                "id": "0",
                "ABV": "SOLAR",
                "location": "Wuppertal, Germany",
                "desc": "really exciting project link <a href='https://sde21.eu/'>here</a>"
            },
            {
                "desc": "really exciting project link <a href='https://uni.xyz/competitions/proximity-island/info/about?utm_medium=website&utm_source=archdaily.com'>here</a>",
                "name": "Proximity",
                "id": "1",
                "ABV": "PROX",
                "location": "Italy"
            },
            {
                "id": "3",
                "ABV": "UNIC",
                "location": "North Sea",
                "desc": "really exciting project <p><img width=100% src='http://agilex.io/F20/reqs/1337/config/img/target.png'>",
                "name": "North Sea University"
            }
        ],
        "additionalProperties": true,
        "required": [
            "name",
            "id",
            "ABV",
            "desc",
            "location"
        ],
        "properties": {
            "name": {
                "$id": "#/items/properties/name",
                "type": "string",
                "title": "The Name Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "Solar Decathalon"
                ]
            },
            "id": {
                "$id": "#/items/properties/id",
                "type": "string",
                "title": "The Id Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "0"
                ]
            },
            "ABV": {
                "$id": "#/items/properties/ABV",
                "type": "string",
                "title": "The Abv Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "SOLAR"
                ]
            },
            "desc": {
                "$id": "#/items/properties/desc",
                "type": "string",
                "title": "The Desc Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "really exciting project link <a href='https://sde21.eu/'>here</a>"
                ]
            },
            "location": {
                "$id": "#/items/properties/location",
                "type": "string",
                "title": "The Location Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "Wuppertal, Germany"
                ]
            }
        }
    }
}

=== timmcginley/V3/data/target.json
[{
		"name": "Solar Decathalon",
		"id": "0",
		"ABV": "SOLAR",
		"desc": "really exciting project link <a href='https://sde21.eu/'>here</a>",
		"location": "Wuppertal, Germany"
	},
	{
		"name": "Proximity",
		"id": "1",
		"ABV": "PROX",
		"desc": "really exciting project link <a href='https://uni.xyz/competitions/proximity-island/info/about?utm_medium=website&utm_source=archdaily.com'>here</a>",
		"location": "Italy"

	},
	{
		"name": "North Sea University",
		"id": "3",
		"ABV": "UNIC",
		"desc": "really exciting project <p><img width=100% src='http://agilex.io/F20/reqs/1337/config/img/target.png'>",
		"location": "North Sea"

	},
	{
		"name": "310",
		"id": "4",
		"ABV": "310",
		"desc": "This project is pretty awesome...",
		"location": "DTU Lyngby"

	}


]
